/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
  // Apply the application plugin to add support for building a CLI application in Java.
  application
  antlr
  jacoco
//  checkstyle
  id("com.diffplug.spotless") version "6.25.0"
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  // Use JUnit test framework.
  testImplementation("org.junit.jupiter:junit-jupiter:5.10.1")

  // Mockito Core
  testImplementation("org.mockito:mockito-core:5.11.0")

  // Mockito + JUnit5 integration
  testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")

  // This dependency is used by the application.
  implementation(libs.guava)

  antlr("org.antlr:antlr4:4.13.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

application {
  // Define the main class for the application.
  mainClass = "dev.xxdb.server.XxdbServer"
}

tasks.test { useJUnitPlatform() }
tasks.test {
    useJUnitPlatform()
    jvmArgs("-XX:+EnableDynamicAgentLoading")
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
        csv.required.set(true)
    }
}

//checkstyle {
//    toolVersion = "10.12.4" // or your preferred version
//    configFile = file("$rootDir/app/config/checkstyle/checkstyle.xml")
//}

spotless {
    java {
        googleJavaFormat("1.17.0")
    }
}

