name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew -p app build --no-daemon
      - name: Run tests with coverage
        run: ./gradlew -p app jacocoTestReport --no-daemon
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: app/build/reports/jacoco/test/html
      - name: Generate coverage badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: app/build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges
      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: .github/badges

  # Optionally, you can add a job to comment the badge on PRs or push it to gh-pages for display 